services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /run/user/1000/docker.sock:/tmp/docker.sock:ro
    
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      VIRTUAL_HOST: plex.local
      VIRTUAL_PORT: "32400"
      TZ: ${LPC_TIMEZONE}
      PLEX_CLAIM: ${LPC_PLEX_CLAIM}
      ADVERTISE_IP: http://plex.local/
      PUID: "0"
      PGID: "0"
      UMASK: "022"
    hostname: plex.local
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./data/media:/data/media

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    hostname: sonarr.local
    volumes:
      - ./sonarr:/config
      - ./data:/data
    environment:
      VIRTUAL_HOST: sonarr.local
      VIRTUAL_PORT: "8989"
      PUID: "0"
      PGID: "0"
      UMASK: "022"
    depends_on:
      - jackett
      - flaresolverr

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    hostname: radarr.local
    volumes:
      - ./radarr:/config
      - ./data:/data
    environment:
      VIRTUAL_HOST: radarr.local
      VIRTUAL_PORT: "7878"
      PUID: "0"
      PGID: "0"
      UMASK: "022"
    depends_on:
      - jackett
      - flaresolverr

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: qbittorrent.local
      VIRTUAL_PORT: "8068"
      TZ: ${LPC_TIMEZONE}
      WEBUI_PORT: "8068"
      TORRENTING_PORT: "6881"
      PUID: "0"
      PGID: "0"
      UMASK: "022"
    volumes:
      - ./qbittorrent:/config
      - ./data/torrents:/data/torrents
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8068:8068

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: jackett.local
      VIRTUAL_PORT: "9117"
    hostname: jackett.local
    volumes:
      - ./jackett:/config
    depends_on:
      - gluetun
      - flaresolverr

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      LOG_HTML: "false"
      CAPTCHA_SOLVER: none
      TZ: ${LPC_TIMEZONE}

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_LISTENING_ADDRESS: ":8888"
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      VPN_ENDPOINT_IP: ${LPC_VPN_ENDPOINT_IP}
      VPN_ENDPOINT_PORT: ${LPC_VPN_ENDPOINT_PORT}
      WIREGUARD_PUBLIC_KEY: ${LPC_WIREGUARD_PUBLIC_KEY}
      WIREGUARD_PRIVATE_KEY: ${LPC_WIREGUARD_PRIVATE_KEY}
      WIREGUARD_PRESHARED_KEY: ${LPC_WIREGUARD_PRESHARED_KEY}
      WIREGUARD_ADDRESSES: ${LPC_WIREGUARD_ADDRESSES}
