services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /run/user/1000/docker.sock:/tmp/docker.sock:ro
      - ./nignx.conf:/etc/nginx/conf.d/default.conf
    
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      VIRTUAL_HOST: plex.local
      VIRTUAL_PORT: "32400"
      TZ: ${LPC_TIMEZONE}
      PLEX_CLAIM: ${LPC_PLEX_CLAIM}
      ADVERTISE_IP: http://plex.local/
    hostname: plex.local
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./media:/data

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - ./sonarr:/config
      - ./media/serials:/serials
      - ./downloads:/downloads
    # ports:
    #   - 8989:8989
    depends_on:
      - qbittorrent
      - jackett
      - flaresolverr

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - ./radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    # ports:
    #   - 7878:7878
    depends_on:
      - qbittorrent
      - jackett
      - flaresolverr

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      TZ: ${LPC_TIMEZONE}
      WEBUI_PORT: "8068"
      TORRENTING_PORT: "6881"
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8068:8068

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - ./jackett:/config
    depends_on:
      - gluetun
      - flaresolverr

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      LOG_LEVEL: info
      LOG_HTML: "false"
      CAPTCHA_SOLVER: none
      TZ: ${LPC_TIMEZONE}

  gramarrru:
    container_name: gramarrru
    image: memodota/gramarrru
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    volumes:
      - ./gramarr:/config     

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        sonarr.local:
          "/":
            port: 8989
        radarr.local:
          "/":
            port: 7878
        jackett.local:
          "/":
            port: 9117
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      VPN_ENDPOINT_IP: ${LPC_VPN_ENDPOINT_IP}
      VPN_ENDPOINT_PORT: ${LPC_VPN_ENDPOINT_PORT}
      WIREGUARD_PUBLIC_KEY: ${LPC_WIREGUARD_PUBLIC_KEY}
      WIREGUARD_PRIVATE_KEY: ${LPC_WIREGUARD_PRIVATE_KEY}
      WIREGUARD_PRESHARED_KEY: ${LPC_WIREGUARD_PRESHARED_KEY}
      WIREGUARD_ADDRESSES: ${LPC_WIREGUARD_ADDRESSES}
    ports:
      - 8191:8191
      - 9117:9117
      - 7878:7878
      - 8989:8989
