services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${LPC_TIMEZONE}
      - PLEX_CLAIM=${LPC_PLEX_CLAIM}
      - ADVERTISE_IP=http://${LPC_HOSTNAME}:32400/
    hostname: ${LPC_HOSTNAME}
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./media:/data

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - ./media/serials:/serials
      - ./downloads:/downloads
    ports:
      - 8989:8989
    depends_on:
      - qbittorrent
      - jackett

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    depends_on:
      - qbittorrent
      - jackett

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      - TZ=${LPC_TIMEZONE}
      - WEBUI_PORT=8068
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8068:8068

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117

  torproxy:
    container_name: torproxy
    build:
      context: .
      dockerfile: Dockerfile.torproxy
    restart: unless-stopped
    environment:
      - BRIDGE1=${LPC_TOR_BRIDGE1}
      - BRIDGE2=${LPC_TOR_BRIDGE2}
    ports:
      - 8118:8118

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${LPC_TIMEZONE}
    ports:
      - 8191:8191

  gramarrru:
    container_name: gramarrru
    image: memodota/gramarrru
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    volumes:
      - ./gramarr:/config     
